name: Build

on:
  push:
    branches: [ patch-2 ]
  pull_request:
    branches: [ patch-2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Grant all permissions for theme
        run: sudo chmod -R 777 theme
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk16
          arguments: genSources build
          gradle-version: wrapper
      - name: Setup the artifact uploader
        run: |
          cd build/libs
          export LB_VERSION=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          cp $LB_VERSION liquidbounce.jar
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: build/libs/liquidbounce.jar
